package org.openi.wcf.component;

/**
 * 
 * @author SUJEN
 *
 */
public enum WCFComponentType {
	NAVIGATOR, TABLE, CHART, PRINT, PRINTFORM, MDXEDITFORM, CHARTPROPERTIESFORM, SORTFORM, DRILLTHROUGHTABLE, HIERARCHYNAVIGATOR, MEMBERNAVIGATOR
}
